Sprint 8 solution time and duration
jsavchenkova/java-kanban pull request #3
Opened 2024-04-18 14:37 UTC by jsavchenkova

2024-04-19 15:00 UTC, kriwsha requested changes

2024-04-19 15:00 UTC, kriwsha commented on src/resources/1t.csv
> +id,type,name,status,description,epic,start,finish,duration
Вообще файлы, не связанные с кодом (грубо говоря, не java файлы), следует выносить из src директории

2024-04-19 15:00 UTC, kriwsha commented on src/ya/tasktracker/manager/InMemoryTaskManager.java
> +        subTasks.values().stream().mapToInt(SubTask::getId).forEach(inMemoryHistoryManager::remove);
Для лучшего чтения кода я бы рекомендовал стрим разбивать на строки по операциям

2024-04-19 15:00 UTC, kriwsha commented on src/ya/tasktracker/manager/InMemoryTaskManager.java
> +    public Optional<Task> getTask(int id) {
Спорное решение - возвращать Optional. Во-первых, в ТЗ указано, что эти методы должны возвращать объект задачи. С другой стороны, представьте, что ваш код - это библиотека, которую будут использовать в другом проекте. И не всегда будет удобно получать Optional вместо null.

2024-04-19 17:45 UTC, jsavchenkova commented on src/ya/tasktracker/manager/InMemoryTaskManager.java
> +    public Optional<Task> getTask(int id) {
Оставлю пока как есть :)

2024-04-20 16:28 UTC, kriwsha approved these changes

2024-04-20 19:59 UTC, merged